# Generated by Django 4.2.7 on 2025-09-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='Original article URL', max_length=2048)),
                ('original_content', models.TextField(help_text='Scraped text from the URL')),
                ('user_prompt_adjustment', models.TextField(blank=True, help_text="User's prompt modifications", null=True)),
                ('linkedin_post', models.TextField(help_text='Generated LinkedIn post text')),
                ('summary', models.TextField(help_text='Generated summary')),
                ('business_rationale', models.TextField(help_text='Business importance rationale')),
                ('image_url_1', models.URLField(blank=True, help_text='First generated image in S3', max_length=2048, null=True)),
                ('image_url_2', models.URLField(blank=True, help_text='Second generated image in S3', max_length=2048, null=True)),
                ('markdown_content', models.TextField(help_text='Complete markdown output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Generated Post',
                'verbose_name_plural': 'Generated Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
