# Generated by Django 4.2.7 on 2025-09-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='images_completed_at',
            field=models.DateTimeField(blank=True, help_text='When image generation completed', null=True),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='images_processing',
            field=models.BooleanField(default=False, help_text='Whether images are currently being generated'),
        ),
    ]
