# Generated by Django 4.2.7 on 2025-09-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_generatedpost_images_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='image_prompt_1',
            field=models.TextField(blank=True, help_text='AI-generated prompt used for first image', null=True),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='image_prompt_2',
            field=models.TextField(blank=True, help_text='AI-generated prompt used for second image', null=True),
        ),
    ]
